### ISSUE TITLE
z-index issue maybe?

### ISSUE THREAD

**Issue by oeowen** [paulo-raca/highcharts-draggable-3d#8]
I'm not sure if the problem is in the draggable 3d area or the highcharts 3d rendering, but if you spin the example through approximately 180 degrees you can see that the light blue columns in the middle pop in front of the red columns. It seems the z-index is incorrect. Am I doing something wrong? 

https://jsfiddle.net/7cjtjo7y/3/

**Comment by paulo-raca** [comment]
This particular issue is on highcharts 3d rendering.

Turns out that properly calculating the z-order os 3D elements is terribly difficult, and it uses simple heuristics instead. I've sent a few patches to improve on this, but as you noticed, still far from perfect.

If I'm not mistaken, the current heuristic used the Z of the centroid of each bar as the Z order. It's a good heuristic, but doesn't work well for large objects. Other (better) heuristics should be possible, if you want to work on it.

 E.g., In particular for bar charts, it would probably work well to project the centroid on `Y=0` (`X = 0` if they are horizontal bars) before calculating it's Z (And probably add the non-projected centroid's Z * 0.001 as a tie-breaker for stacked bars)

**Comment by paulo-raca** [comment]
That's weird. As far as I recall, the Z-order was recalculated at every redraw. 

Well, I haven't worked on this for a while (And they have changed it a lot since), maybe they are no longer recomputing z-order?

**Comment by oeowen** [comment]
I'll have to see if I can work out how to force the Z-order to recalculate, at least once on the mouse-up. Maybe a Redraw() with a "force z-index" parameter?

This could take me a while!!!
